server:
  port: 6010
spring:
  cloud:
    config:
      server:
        git:
          uri: 'https://codehub-cn-south-1.devcloud.huaweicloud.com/djzx/dangjia-server.git'
          searchPaths: 'config'
          clone-on-start: true
          username: 'qiyuxiang'
          password: 'Xinxin813806'
          default-label: master
          timeout: 10
        encrypt:
          enabled: false
  application:
    name: 'config'
logging:
  config: classpath:logback-spring.xml

#  eureka:
#    client:
#      service-url:
#        defaultZone: 'http://discovery:8888/eureka/'

