server:
  port: 8888
eureka:
  server:
    responseCacheUpdateInvervalMs: 3000
    eviction-interval-timer-in-ms: 3000
    enable-self-preservation: false
  instance:
    hostname: 192.168.0.229
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: dangjia-eureka
